### ISSUE TITLE
Spline interpolation not displaying correctly in Safari

### ISSUE THREAD

**Issue by davibicudo** [Simsso/Online-Tools#2]
Cubic Spline interpolation using example points viewed in Safari (desktop):
<img width="506" alt="screen shot 2017-08-22 at 11 23 07" src="https://user-images.githubusercontent.com/28100741/29558426-531ae4ac-872c-11e7-865a-712c5cd92fc6.png">
In Chrome it works fine:
<img width="509" alt="screen shot 2017-08-22 at 11 23 14" src="https://user-images.githubusercontent.com/28100741/29558432-55f504fa-872c-11e7-8479-1a521a7fb450.png">

Safari version: 10.1.2 (12603.3.8)

**Comment by Simsso** [comment]
Thanks a lot for reporting!
I will take a look at it as soon as possible.

**Comment by Simsso** [comment]
Hi there,
I was not able to reproduce the behavior on my Mac (exact same browser version). Could you @davibicudo provide more detailed system information please? Thanks a lot.

![screen shot 2017-08-24 at 22 28 22](https://user-images.githubusercontent.com/6556307/29687120-98efb3b8-891b-11e7-8090-87bdbe2af3ef.png)

**Comment by davibicudo** [comment]
Now it's working also here! I don't know if I can reproduce the problem again. I guess you can close the issue :)
